defaults:
  #- env: carl_mountain_car
  - brax_ant.yaml
  - override hydra/launcher: slurm
  - _self_ # this indicates that the current config overrides the configs placed above it
           # however, this is already the default behavior, so this line is not necessary


hydra:
  callbacks:
    log_job_return:
      _target_: hydra.experimental.callbacks.LogJobReturnCallback
  job:
    chdir: True

  sweeper:    # only invoked if --multirun is used, e.g. `python launchers/train_ae.py --multirun`
    params:
      context.mode: explicit, hidden, default_value, learned_jrpl 
      seed: range(10)
  run:
    dir: results/hydra/single_run/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: results/hydra/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/${env.id}/${context.mode}/${seed}
    subdir: ${hydra.job.num}

wandb:
  track: True
  project_name: meta_rl
  entity: 

capture_video: True

seed: 0

context:
  mode:  explicit #, hidden, learned_iida, default_value, learned_jrpl
  lower_bound_coeff: 0.2 # lower bound = lower_bound_coeff * context_default
  upper_bound_coeff: 2.0 # upper bound = upper_bound_coeff * context_default
  nb_evals_per_seed: 1
  
  
context_encoder:
  nb_input_transitions: 20
  hidden_sizes: [8, 4]
  latent_context_dim: 2

sac_params:
  autotune_entropy: True