context:
  name: power
  train_values : [-5, -3, -1, 1, 3, 5]
  eval_values :  [-10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10]

env:
  id: CARLMountainCarContinuous
  max_episode_steps: 999

train:
  total_timesteps: 30000