id: CARLCartPoleContinuous
max_episode_steps: 200
total_train_timesteps: 30000
context:
  name: force_mag
  train_values: [25, 35, 45, 55, 65, 75]
  eval_values: [1, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

  