defaults:
  - algorithm: dqn
  - search_space: dqn
  - override hydra/sweeper: DEHB
# if you want to use slurm, uncomment here and below:
  - override hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: ml_gpu-rtx2080
    cpus_per_task: 1
    mem_gb: 1
    gres: null
    timeout_min: 10

  sweeper:
    budget_variable: algorithm.total_timesteps
    dehb_kwargs:
      mutation_factor: 0.2
      max_budget: ${algorithm.total_timesteps}
      min_budget: 1e5
      wandb_project: dehb_for_cartpole_dqn_jrpl
      wandb_entity: # your wandb entity
      deepcave: false
    search_space: ${search_space}
    total_brackets: 5
  run:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./tmp/${now:%Y-%m-%d}/${now:%H-%M-%S}
    

env_name: CartPole-v1
load: false
save: false
reward_curves: false
